/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, builtinclass, uuid(0f0b6e80-5b0d-404e-99d2-9e1a3bfac3a5)]
interface nsIFloorpMacPwa : nsISupports
{
  /**
   * Creates (or updates) an application bundle for a Floorp SSB.
   *
   * @param bundlePath Absolute path to the .app bundle that should be created.
   * @param appName Human readable application name.
   * @param bundleIdentifier Unique CFBundleIdentifier for the bundle.
   * @param appId Floorp internal PWA identifier.
   * @param startUrl Launch URL associated with the PWA.
   * @param floorpExecutablePath Absolute path to the Floorp binary.
   * @param profileDir Absolute path of the Floorp profile.
   * @param profileName Human readable profile name (used for diagnostics).
   * @param versionString Version string to embed in the bundle metadata.
   * @param iconSourcePath Optional path to an image file that should become
   *        the bundle icon. Pass an empty string to skip icon generation.
   */
  void createOrUpdateApp(in AString bundlePath,
                         in AString appName,
                         in AString bundleIdentifier,
                         in AString appId,
                         in AString startUrl,
                         in AString floorpExecutablePath,
                         in AString profileDir,
                         in AString profileName,
                         in AString versionString,
                         in AString iconSourcePath);

  /**
   * Removes an application bundle from disk.
   *
   * @param bundlePath Absolute path to the .app bundle to remove.
   */
  void removeApp(in AString bundlePath);
};

