# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) 📅 Daily Build with Pull Upstream"

on:
  schedule:
    - cron: '0 6 */3 * *'
  workflow_dispatch:

run-name: "Daily Build with Pull Upstream"
jobs:
  part-1:
    name: Pull Upstream from Mozilla-Central
    uses: ./.github/workflows/pull-upstream.yml
    secrets: inherit

  windows-amd64:
    name: Windows amd x64 build
    needs: part-1
    uses: ./.github/workflows/wrapper_windows_build.yml
    secrets: inherit
    with:
      debug: false
      pgo: false

  linux-amd64:
    name: Linux amd x64 build
    needs: part-1
    uses: ./.github/workflows/wrapper_linux_build.yml
    secrets: inherit
    with:
      debug: false
      pgo: false

  mac-amd64:
    name: Mac amd x64 build
    needs: part-1
    uses: ./.github/workflows/wrapper_mac_build.yml
    secrets: inherit
    with:
      debug: false
      pgo: false

  platform-tests:
    name: Platform Tests
    needs: [windows-amd64, linux-amd64, mac-amd64]
    uses: ./.github/workflows/patch-test.yml
    with:
      platform: ubuntu

  test-results:
    name: Collect Test Results
    if: always()
    needs: platform-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          NC='\033[0m'
          status="${{ needs.platform-tests.outputs.test_status }}"
          echo "=== Test Results Summary ==="
          if [[ "$status" == "success" ]]; then
            echo -e "${GREEN}✓ Test passed${NC}"
          else
            echo -e "${RED}✗ Test failed${NC}"
            echo "::warning::Platform test failed"
          fi
          echo "Overall status: ${status}"
          if [[ "$status" == "failure" ]]; then
            echo "::warning::One or more platform tests failed"
          fi

  release:
    name: Publish Dev Release
    needs: [test-results, platform-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Determine tag based on patch test status
        id: set_tag
        shell: bash
        run: |
          if [ "${{ needs.platform-tests.outputs.test_status }}" = "success" ]; then
            tag="dev-passed-latest"
          else
            tag="dev-failed-$(date +%Y%m%d%H%M%S)"
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: floorp-win-amd64-moz-artifact
          path: ./artifact/win

      - name: Zip Windows Artifact
        run: |
          cd ./artifact/win
          zip -r ./floorp-win-amd64-moz-artifact.zip .

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: floorp-linux-amd64-moz-artifact
          path: ./artifact/linux

      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: floorp-mac-universal-moz-artifact-dev
          path: ./artifact/mac

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          name: "Runtime Release - ${{ steps.set_tag.outputs.tag }}"
          body: "This is a nightly build of Runtime. The Patch Test status is ${{ needs.platform-tests.outputs.test_status }}."
          files: |
            ./artifact/win/floorp-win-amd64-moz-artifact.zip
            ./artifact/linux/floorp-linux-amd64-moz-artifact.tar.xz
            ./artifact/mac/floorp-macOS-universal-moz-artifact.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
