---
# SPDX-License-Identifier: MPL-2.0

name: iOS Build Wrapper

'on':
  workflow_dispatch:

  workflow_call:

run-name: iOS Build

jobs:
  get-buildid:
    runs-on: ubuntu-latest
    outputs:
      buildids: ${{ steps.get.outputs.bid }}
    steps:
      - id: get
        shell: bash -xe {0}
        run: |
          bdat=`date +"%Y%m%d%I%M%S"`
          echo "bid=${bdat}" >> $GITHUB_OUTPUT

  ios-simulator:
    needs: [get-buildid]
    uses: ./.github/workflows/ios-build.yml
    secrets: inherit
    with:
      MOZ_BUILD_DATE: ${{ needs.get-buildid.outputs.buildids }}
