# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{6344f783-c893-4db8-91ec-7d43a46bd6f4}',
        'contract_ids': [
            '@mozilla.org/browser/ssb/clh;1',
        ],
        'esModule': 'resource://noraneko/modules/pwa/SsbCommandLineHandler.sys.mjs',
        'constructor': 'SSBCommandLineHandler',
        'categories': {
            'command-line-handler': 'e-ssb',
        },
    },
]

if buildconfig.substs['MOZ_WIDGET_TOOLKIT'] == 'gtk':
    Classes += [
        {
            'cid': '{d99f0c02-5b68-4c44-8f10-cfdd1ee53c74}',
            'contract_ids': [
                '@noraneko.org/pwa/linux-taskbar;1',
            ],
            'type': 'mozilla::FloorpLinuxTaskbar',
            'headers': [
                '/.github/assets/pre-build/pwa/linux/FloorpLinuxTaskbar.h',
            ],
        },
    ]

if buildconfig.substs['MOZ_WIDGET_TOOLKIT'] == 'cocoa':
    Classes += [
        {
            'cid': '{1a4a3d30-7d0c-4ca1-9dbb-73565cffd1c5}',
            'contract_ids': [
                '@noraneko.org/pwa/mac-app-support;1',
            ],
            'type': 'mozilla::FloorpMacPwa',
            'headers': [
                '/.github/assets/pre-build/pwa/mac/FloorpMacPwa.h',
            ],
        },
    ]
